# Minimal Test Configuration
# Purpose: Test pipeline with 2 utterances on minimal hardware
# Expected: Overfitting to 2 samples, but validates pipeline

# -- Data Configuration (minimal) --
data:
  dataset_path: "data/processed/linguistic_features_with_audio_paths.json"
  train_files: "data/processed/train_files.txt"
  val_files: "data/processed/val_files.txt"
  input_features: ["phoneme_id", "pos_tag", "syllable_stress", "word_stress", "sentence_stress", "boundary_tone", "focus_marking", "topic_marking", "givenness", "definiteness", "animacy", "number", "gender", "case", "tense"]
  batch_size: 1  # Minimal batch size
  num_workers: 0  # No multiprocessing
  pin_memory: false  # Disable for minimal memory
  shuffle: false  # Deterministic for testing
  val_split: 0.5  # 50% split for 2 samples
  random_seed: 42

# -- Audio Configuration --
audio:
  sampling_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80
  f_min: 0
  f_max: 8000
  f0_min: 50
  f0_max: 800
  f0_bin_size: 256
  energy_threshold: 0.1
  duration_min: 0.1
  duration_max: 10.0

# -- Model Architecture (minimal) --
model:
  architecture_type: "transformer"
  
  # MLP prosody predictor (minimal)
  prosody_predictor:
    name: "mlp"
    input_dim: 272
    hidden_dims: [128, 64]  # Smaller layers
    output_dim: 272
    dropout: 0.0  # No dropout for overfitting
    activation: "relu"
    batch_norm: false  # Disable for minimal memory
    
  # Phoneme encoder (minimal)
  phoneme_encoder:
    embedding_dim: 128  # Smaller embedding
    n_layers: 2  # Fewer layers
    hidden_dim: 128  # Smaller hidden dim
    dropout: 0.0  # No dropout
    max_phoneme_length: 50  # Shorter sequences
    
  # Spectrogram decoder (minimal)
  spectrogram_decoder:
    n_layers: 3  # Fewer layers
    hidden_dim: 129  # Encoded features (128) + duration (1)
    output_dim: 80
    dropout: 0.0  # No dropout
    
  # Vocoder configuration
  vocoder:
    name: "hifigan"
    checkpoint_path: "checkpoints/hifigan.pt"
    sample_rate: 22050

# -- Training Configuration (minimal) --
training:
  # Optimization
  optimizer: "AdamW"
  learning_rate: 0.001
  weight_decay: 0.0  # No regularization for overfitting
  betas: [0.9, 0.999]
  eps: 1e-8
  
  # Learning rate scheduling
  scheduler: "cosine"
  warmup_steps: 50
  
  # MINIMAL: Very short training
  max_epochs: 5  # Just 5 epochs
  max_steps: null
  
  # Early stopping (relaxed)
  early_stopping_patience: 10
  early_stopping_min_delta: 0.001
  
  # Gradient handling
  gradient_clip_val: 1.0
  gradient_clip_norm: null
  
  # Mixed precision (disable for minimal)
  use_amp: false
  precision: "32"
  
  # Checkpointing (minimal)
  save_top_k: 1
  save_last: false
  save_every_n_epochs: 1
  
  # Validation (frequent)
  val_check_interval: 1.0
  num_sanity_val_steps: 1

# -- Loss Configuration --
loss:
  # Loss weights
  mel_loss_weight: 1.0
  duration_loss_weight: 1.0
  f0_loss_weight: 1.0
  energy_loss_weight: 0.5
  
  # Loss functions
  mel_loss: "l1"
  duration_loss: "mse"
  f0_loss: "mse"
  energy_loss: "mse"
  
  # Additional loss terms
  use_kl_loss: false
  kl_loss_weight: 0.0

# -- Experiment Configuration (minimal) --
experiment:
  output_dir: null
  monitor: "val_loss"
  mode: "min"
  save_checkpoint_every_n_epochs: 1
  
  # Minimal logging
  log_every_n_steps: 1  # Log every step
  log_every_n_epochs: 1
  
  # TensorBoard logging (minimal)
  log_gradients: false
  log_learning_rate: true
  log_histograms: false
  log_audio_every_n_epochs: 1  # Log audio every epoch
  log_audio_samples: 2  # Both samples
  save_best_model: true

# -- Evaluation Configuration (minimal) --
evaluation:
  metrics:
    - "duration_rmse"
    - "f0_rmse"
    - "energy_rmse"
    - "mel_l1_loss"
    - "mel_l2_loss"
    - "overall_loss"
  generate_audio_every_n_epochs: 1
  num_eval_samples: 2
  test_sentences:
    - "Test utterance one."
    - "Test utterance two."

# -- Hardware Configuration (minimal) --
hardware:
  gpus: 0  # CPU only for minimal requirements
  accelerator: "cpu"
  devices: 1
  accumulate_grad_batches: 1
  sync_batchnorm: false
  precision: "32"
  deterministic: true

# -- Debugging Configuration (minimal) --
debug:
  debug_mode: true
  fast_dev_run: false
  limit_train_batches: 2  # Only 2 batches
  limit_val_batches: 2  # Only 2 batches
  enable_profiler: false
  profiler_filename: "minimal_test_profile"
  track_grad_norm: true
  log_memory_usage: true

# -- Reproducibility --
reproducibility:
  seed: 42
  deterministic: true
  cudnn_benchmark: false
  cudnn_deterministic: true 